name: Nightly Release to GitHub and PyPi

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: "The release version number (i.e. 1.0.0b1)"
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  dummy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Display Version
        run: |
          echo ${{ inputs.version_number }}
